# Generated by Django 4.2.9 on 2024-04-16 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problems", "0002_remove_problem_author_id_problem_author_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("duel", "0002_delete_duel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Duel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(unique=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competitors",
                    models.ManyToManyField(to=settings.AUTH_USER_MODEL),
                ),
                ("problems", models.ManyToManyField(to="problems.problem")),
            ],
            options={
                "verbose_name": "дуэль",
                "verbose_name_plural": "дуэли",
            },
        ),
    ]
