# Generated by Django 4.2.11 on 2024-04-22 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notes", "0002_remove_note_user_id_note_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="user_dislikes",
            field=models.ManyToManyField(
                related_name="note_dislikes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="user_likes",
            field=models.ManyToManyField(
                related_name="note_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
