stages:
  - linting

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  before_script:
    - pip install -r requirements/test.txt
  script:
    - flake8 --append-config setup.cfg .

black:
  stage: linting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --diff --check --verbose -- .
