stages:
  - flake
  - black

before_script:
  - pip install -r requirements/test.txt

flake8:
  stage: flake
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - cd django
    - flake8 .


black:
  stage: black
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check .
