# Generated by Django 4.2.11 on 2024-04-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="type",
            new_name="notification_type",
        ),
        migrations.AddField(
            model_name="notification",
            name="text",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
