# Generated by Django 4.2.9 on 2024-04-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="text",
            field=models.CharField(blank=True, max_length=511, null=True),
        ),
    ]
