# Generated by Django 4.2.9 on 2024-04-16 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="type",
            new_name="notification_type",
        ),
    ]
