# Generated by Django 4.2.9 on 2024-04-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_id", models.IntegerField(default=1)),
                ("title", models.CharField(max_length=255)),
                (
                    "tests_file",
                    models.FileField(upload_to="tasks_attaches/tests/"),
                ),
                (
                    "answer_file",
                    models.FileField(upload_to="tasks_attaches/answers/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("HR", "Hard-reject"),
                            ("SR", "Soft-reject"),
                            ("AC", "Accepted"),
                        ],
                        default="AC",
                        max_length=2,
                    ),
                ),
                ("text", models.TextField(blank=True, default="", null=True)),
                (
                    "hard_reject_accumulation",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("day_task", models.BooleanField(default=False)),
                ("week_task", models.BooleanField(default=False)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_column="created_at", null=True
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_column="updated_at", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "задача",
                "verbose_name_plural": "задачи",
            },
        ),
    ]
