# Generated by Django 4.2.11 on 2024-04-21 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0002_remove_problem_author_id_problem_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="duration",
            field=models.DurationField(
                default=datetime.timedelta(seconds=900),
                help_text="Укажите время выполнения задачи",
                verbose_name="время на выполнение задачи",
            ),
        ),
    ]
