# Generated by Django 4.2.9 on 2024-04-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problems", "0001_initial"),
        ("notes", "0001_initial"),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="note",
            field=models.ManyToManyField(
                related_name="tag", related_query_name="tag", to="notes.note"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="problem",
            field=models.ManyToManyField(to="problems.problem"),
        ),
    ]
