# Generated by Django 4.2.11 on 2024-04-21 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0003_user_easy_problems_user_games_played_user_games_won_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
