# Generated by Django 4.2.11 on 2024-04-22 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_user_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
