# Generated by Django 4.2.11 on 2024-04-24 12:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                blank=True,
                help_text="укажите дату рождения",
                null=True,
                validators=[core.models.valid_birthday],
                verbose_name="дата рождения",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="загрузите автарку",
                null=True,
                upload_to=core.models.get_path_image,
                verbose_name="аватарка",
            ),
        ),
    ]
