# Generated by Django 4.2.9 on 2024-04-16 18:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0002_alter_group_options_remove_group_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="user",
            field=models.ManyToManyField(
                through="groups.GroupUser", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
