# Generated by Django 5.0 on 2024-04-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0008_alter_groupinvite_accept"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupinvite",
            name="accept",
            field=models.BooleanField(
                choices=[(1, "Принять"), (0, "Отклонить")], default=0
            ),
        ),
    ]
