# Generated by Django 4.2.11 on 2024-04-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0010_alter_groupuser_user"),
        ("groups", "0010_group_title"),
    ]

    operations = []
