# Generated by Django 4.2.11 on 2024-04-24 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0011_merge_0010_alter_groupuser_user_0010_group_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
