# Generated by Django 4.2.11 on 2024-04-26 21:14

from django.db import migrations, models
import groups.models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0012_alter_groupuser_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите аватарку",
                null=True,
                upload_to=groups.models.get_path_image,
                verbose_name="аватарка",
            ),
        ),
        migrations.AddField(
            model_name="group",
            name="theme",
            field=models.CharField(
                blank=True,
                default="Для развлечения",
                help_text="Определитесь с тематикой группы(например 'для развлечения''друзья' и тд.)",
                max_length=30,
                verbose_name="тематика",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="description",
            field=models.TextField(
                help_text="Опишите группу", verbose_name="описание"
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="В публичную группу могут вступить все желающие",
                verbose_name="публичная ли группа?",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="name",
            field=models.CharField(
                help_text="Придумайте уникальное название",
                max_length=255,
                unique=True,
                verbose_name="никнейм",
            ),
        ),
        migrations.AlterField(
            model_name="group",
            name="title",
            field=models.CharField(
                default="Group",
                help_text="Придумайте крутое название для своей группы",
                max_length=255,
                verbose_name="название",
            ),
        ),
    ]
