# Generated by Django 4.2.11 on 2024-04-24 17:09

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_user_birthday_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                blank=True,
                help_text="Укажите дату рождения",
                null=True,
                validators=[core.models.valid_birthday],
                verbose_name="дата рождения",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="github_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="ссылка на ваш github"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gitlab_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="ссылка на ваш gitlab"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите аватарку",
                null=True,
                upload_to=core.models.get_path_image,
                verbose_name="аватарка",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="shortname",
            field=models.CharField(
                blank=True,
                help_text="Введите свое имя(настояшее или вымышленное,             главное - чемпионское)",
                max_length=16,
                null=True,
                verbose_name="имя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Придумайте уникальное имя пользователя",
                max_length=16,
                unique=True,
                verbose_name="имя пользователя",
            ),
        ),
    ]
