# Generated by Django 4.2.11 on 2024-04-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0010_group_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat",
                        related_query_name="chat",
                        to="groups.group",
                    ),
                ),
            ],
            options={
                "verbose_name": "чат",
                "verbose_name_plural": "чаты",
            },
        ),
    ]
