# Generated by Django 4.2.9 on 2024-04-04 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "profile",
            "0002_remove_achievements_profile_achievements_user_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievements",
            name="user_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                related_query_name="achievements",
                to="profile.customprofile",
            ),
        ),
        migrations.AlterField(
            model_name="problem",
            name="user_id",
            field=models.ManyToManyField(
                related_name="problem",
                related_query_name="problem",
                to="profile.customprofile",
            ),
        ),
    ]
