# Generated by Django 4.2.9 on 2024-04-06 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="achievementimage",
            name="image",
            field=models.ImageField(upload_to="image/achievements/"),
        ),
    ]
