# Generated by Django 4.2.11 on 2024-04-22 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Submission",
        ),
    ]
