# Generated by Django 4.2.11 on 2024-04-24 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submissions", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="exec_time",
            field=models.IntegerField(
                default=-1, verbose_name="Время выполнения"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="verdict",
            field=models.CharField(
                default="", max_length=127, verbose_name="Вердикт"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="score",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Оценка",
            ),
        ),
    ]
